services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: next-login
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # web:
  #   image: node:20-alpine
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://user:user123@db:5432/next-login

volumes:
  pgdata:
    driver: local
